name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        - os: ubuntu-22.04
          python-version: ["3.10", "3.11", "3.12"]
        - os: windows-latest  
          python-version: ["3.10", "3.11", "3.12"]
        - os: macos-14
          python-version: "3.12"
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/huggingface
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      
      - name: Install dependencies
        run: pip install -e '.[lint,test]'
      
      - name: Lint
        run: ruff check .
      
      - name: Test  
        run: pytest --cov=scaleforge --maxfail=1
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
      
      - name: Build package
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.12'
        run: python -m build
      
      - name: Upload artifacts
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
