name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build deps
        run: |
          python -m pip install -U pip
          pip install build twine
      - name: Build
        run: python -m build
      - name: Check
        run: twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: scaleforge-dist
          path: dist/*
      - name: Publish to TestPyPI
        if: secrets.TEST_PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: >-
          startsWith(github.ref, 'refs/tags/v') &&
          !contains(github.ref, 'a') &&
          !contains(github.ref, 'b') &&
          !contains(github.ref, 'rc') &&
          secrets.PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
